name: Publish NPM Package

on:
  release:
    types: [created]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm test
      - run: npm version --allow-same-version --no-git-tag-version ${{ github.event.release.tag_name }}
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
